---
  - name: Use command module to download Filebeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
 
  - name: Use command line to install Metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb
  
  - name: Use copy function to pull config file
    copy:
      src: /etc/ansible/roles/install-metricbeat/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
  
  - name: Use command line to enable and configure docker module
    command: metricbeat modules enable docker
  
  - name: Use command to set up metricbeat
    command: metricbeat setup
  
  - name: Use command to start metricbeat
    command: service metricbeat start
  
  - name: Enable start up on boot
    systemd:
      name: metricbeat
      enabled: yes
